// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRg_BlupzEMYSIzg_6ZTNClvGoVtQryzI',
    appId: '1:700842510639:web:d7ed9faa0d3c54dd2df9da',
    messagingSenderId: '700842510639',
    projectId: 'expense-tracker-ba653',
    authDomain: 'expense-tracker-ba653.firebaseapp.com',
    storageBucket: 'expense-tracker-ba653.firebasestorage.app',
    measurementId: 'G-VE4L3Q9CWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX3ltIm-YSqu_eqIqL1_FFVJumJbBugZ4',
    appId: '1:700842510639:android:3d06deb9c9d42ade2df9da',
    messagingSenderId: '700842510639',
    projectId: 'expense-tracker-ba653',
    storageBucket: 'expense-tracker-ba653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73mx8ST8og86bD9uunjyp-WUaYNj7EPg',
    appId: '1:700842510639:ios:2bd8ab8fe4a20a4b2df9da',
    messagingSenderId: '700842510639',
    projectId: 'expense-tracker-ba653',
    storageBucket: 'expense-tracker-ba653.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73mx8ST8og86bD9uunjyp-WUaYNj7EPg',
    appId: '1:700842510639:ios:2bd8ab8fe4a20a4b2df9da',
    messagingSenderId: '700842510639',
    projectId: 'expense-tracker-ba653',
    storageBucket: 'expense-tracker-ba653.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRg_BlupzEMYSIzg_6ZTNClvGoVtQryzI',
    appId: '1:700842510639:web:afee75ca49d7b4022df9da',
    messagingSenderId: '700842510639',
    projectId: 'expense-tracker-ba653',
    authDomain: 'expense-tracker-ba653.firebaseapp.com',
    storageBucket: 'expense-tracker-ba653.firebasestorage.app',
    measurementId: 'G-BJL80H0MXX',
  );
}
